name: run-code
on: [push]
jobs:
  compile-run:
    runs-on: windows-2019
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1.0.5
        with:
          rust-version: stable
      - name: Setup | Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: run
        run: python run.py